version: '3'
services:
  app:
    container_name: docs-backend
    restart: always
    build: .
    ports:
      - 80:4000
    links:
      - mongo
  mongo:
    container_name: mongo
    build: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docs
      - MONGO_INITDB_ROOT_PASSWORD=1205360