version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/minz/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docs
      - MONGO_INITDB_ROOT_PASSWORD=1205360
  app:
    container_name: docs-backend
    restart: always
    build: .
    ports:
      - 80:4000
    links:
      - mongo